___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
my_list = [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]
np.array(my_list)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
my_list1 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1,]
np.array(my_list1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [5]:
my_list = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5,]
np.array(my_list)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
my_mat =[[0, 1, 2],[3, 4, 5],[6, 7, 8]]
np.array(my_mat)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [33]:
np.random.rand(2)

array([0.84996382, 0.73749509])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [36]:
np.random.rand(1,25)

array([[0.86276184, 0.74010413, 0.59650512, 0.57392634, 0.85118919,
        0.97563602, 0.680164  , 0.50714458, 0.18898595, 0.33848347,
        0.67499301, 0.836446  , 0.63302283, 0.13996269, 0.21869921,
        0.82984769, 0.93022246, 0.23293982, 0.45903647, 0.4788787 ,
        0.02539236, 0.31258617, 0.45548994, 0.91728392, 0.29245249]])

#### Create the following matrix:

In [35]:
np.random.rand(5,5)

array([[0.03840757, 0.37026223, 0.58200885, 0.10851053, 0.24831902],
       [0.96435552, 0.10603085, 0.59505698, 0.72569619, 0.04025531],
       [0.94924743, 0.1850693 , 0.35209514, 0.19856461, 0.96983226],
       [0.47603305, 0.56506743, 0.08635402, 0.61863524, 0.98514774],
       [0.92231767, 0.64276779, 0.27389708, 0.0327653 , 0.06144925]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.r

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [10]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [12]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [13]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [14]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [15]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

### Now do the following

#### Get the sum of all the values in mat

#### Get the standard deviation of the values in mat

#### Get the sum of all the columns in mat

# Great Job!